name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./customer-order-management/pom.xml
          mvn clean package -f ./menu-management/pom.xml
          mvn clean package -f ./delivery-management/pom.xml

      - name: Docker Build and push for CustomerOrderManagement
        uses: docker/build-push-action@v4
        with:
          context: ./customer-order-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer-order-management:latest
            ghcr.io/${{ github.repository }}/customer-order-management:${{ github.ref_name }}
            
      - name: Docker Build and push for MenuManagement
        uses: docker/build-push-action@v4
        with:
          context: ./menu-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/menu-management:latest
            ghcr.io/${{ github.repository }}/menu-management:${{ github.ref_name }}
            
      - name: Docker Build and push for DeliveryManagement
        uses: docker/build-push-action@v4
        with:
          context: ./delivery-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery-management:latest
            ghcr.io/${{ github.repository }}/delivery-management:${{ github.ref_name }}
            
