apiVersion: v1
kind: Service
metadata:
  name: customer-order-management
  labels:
    app: customer-order-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-order-management