server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: customer-order-management
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: menu-management
          uri: http://localhost:8083
          predicates:
            - Path=/menus/**, 
        - id: delivery-management
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: customer-order-management
          uri: http://customerOrderManagement:8080
          predicates:
            - Path=/orders/**, 
        - id: menu-management
          uri: http://menuManagement:8080
          predicates:
            - Path=/menus/**, 
        - id: delivery-management
          uri: http://deliveryManagement:8080
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
